[package]
name = "astral-filing-cabinet"
version = "0.1.0"
edition = "2021"

[dependencies]
# basic reporting support
log = "^0.4"
anyhow = "^1"
fern = { version="^0.6", features=["colored"] }

indicatif = "^0.17"
structopt = "^0.3"

# data and metadata
md-5 = "^0.10"
sha1 = "^0.10"
toml = "^0.5"
bincode = "^1.3"
serde = "^1.0"

# support for tree layouts
relative-path = "^1.7"

[[bin]]
name = "afc"
path = "src/main.rs"
